<a href="https://colab.research.google.com/github/YiruiLi2004/MSSP6070/blob/main/Modules/Week_6/Week_6_participation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import os
import subprocess

repo_url = "https://github.com/YiruiLi2004/MSSP6070.git"
repo_path = "/content/MSSP6070"

if not os.path.exists(repo_path):
    subprocess.run(["git", "clone", repo_url], check=True)

os.chdir(repo_path)
print(os.getcwd())

/content/MSSP6070

In [11]:
import pandas as pd
student_data = pd.read_csv("data/Student Performance Data.csv")
student_data.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [12]:
student_data.shape

(1000, 10)

In [13]:
high_admission = lambda df: df[df["admission prospect"] == "high"]
high_students = high_admission(student_data)
high_students.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
4,male,group C,some college,standard,76,78,75,229,none,high
5,female,group B,associate's degree,standard,71,83,78,232,none,high
6,female,group B,some college,standard,88,95,92,275,completed,high

In [14]:
high_students.shape

(356, 10)

In [15]:
type(high_students)

pandas.core.frame.DataFrame

In [16]:
high_students["admission prospect"].value_counts()

admission prospect
high    356
Name: count, dtype: int64